### ISSUE TITLE
Inclusiveness of SD (and AR) in SRS and MIS

### ISSUE THREAD

**Issue by samm82** [smiths/caseStudies#137]
Related to #129 and JacquesCarette/Drasil#924

In the SRS (shown) and the MIS, the constraint is given that SD has to be less than SD<sub>max</sub>, but it should be able to be equal to it (as with _w_), as the definition of SD<sub>max</sub> is the "maximum stand off distance permissible for input" (SRS 1.2). 

I can't find if this explicitly arose in the conversation on #129, but can AR be equal to AR<sub>max</sub>?

![data cons](https://user-images.githubusercontent.com/35857611/43212815-0320871e-9003-11e8-976a-01afb85931c9.png)

## TODO:

- [x] Update Drasil
- [x] Update caseStudies SRS
- [x] Update caseStudies MIS
- [x] Update Input Module Implementation

**Comment by smiths** [comment]
It is somewhat arbitrary to include or exclude the endpoints for these limits.  However, the decisions should be consistent.  As it is now, there is a mix of "less than" and "less than or equal."  I agree that we s should make them all "less than or equal."  Please make this change for both SD and AR.
